package com.github.guikeller.jettyrunner.ui;

import javax.swing.*;
import java.io.File;

/**
 * Used Netbeans to create this
 * @author Gui
 */
public class JettyRunnerConfigurationPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public JettyRunnerConfigurationPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        pathLabel = new javax.swing.JLabel();
        pathField = new javax.swing.JTextField();
        webappLabel = new javax.swing.JLabel();
        webappField = new javax.swing.JTextField();
        classesLabel = new javax.swing.JLabel();
        classesField = new javax.swing.JTextField();
        runOnPortLabel = new javax.swing.JLabel();
        runOnPortField = new javax.swing.JTextField();
        debuggerLabel = new javax.swing.JLabel();
        debuggerField = new javax.swing.JTextField();
        xmlLabel = new javax.swing.JLabel();
        xmlField = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();

        mainPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("IDEA Jetty Runner - Run Jetty Run"));

        pathLabel.setText("Path:");

        webappLabel.setText("WebApp Folder:");

        classesLabel.setText("Classes Folder:");

        runOnPortLabel.setText("Runs on Port:");

        debuggerLabel.setText("Debugger Port:");

        xmlLabel.setText("Jetty XML:");

        browseButton.setText("Browse XML");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addGap(0, 259, Short.MAX_VALUE)
                                                .addComponent(browseButton))
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                                .addGap(4, 4, 4)
                                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(debuggerLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(xmlLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                                                        .addComponent(runOnPortLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(classesLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(webappLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(pathLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(xmlField)
                                                        .addComponent(debuggerField)
                                                        .addComponent(runOnPortField)
                                                        .addComponent(classesField)
                                                        .addComponent(pathField)
                                                        .addComponent(webappField))))
                                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(pathLabel)
                                        .addComponent(pathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(webappLabel)
                                        .addComponent(webappField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(classesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(classesLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(runOnPortLabel)
                                        .addComponent(runOnPortField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(debuggerLabel)
                                        .addComponent(debuggerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(xmlLabel)
                                        .addComponent(xmlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(browseButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pathField.setToolTipText("Eg: /MyWebApp1 (Accepts multiple values) [Mandatory - CSV]");
        webappField.setToolTipText("Eg: /path/to/src/main/webapp (Accepts multiple values) [Mandatory - CSV]");
        classesField.setToolTipText("Eg: /path/to/target/classes (Accepts multiple values) [Mandatory - CSV]");
        runOnPortField.setToolTipText("Eg: 8080 (single value)");
        debuggerField.setToolTipText("Eg: 5007 (single value) [create a 'Remote' conf to debug] ");
        xmlField.setToolTipText("Eg: /path/to/src/main/resources/jetty.xml (Accepts multiple values) [Optional - CSV]");
        browseButton.setToolTipText("You may select multiple files [Optional]");

    }// </editor-fold>

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setMultiSelectionEnabled(Boolean.TRUE);
        int result = fileChooser.showOpenDialog(new JFrame());
        if(result == JFileChooser.APPROVE_OPTION) {
            String paths = new String();
            File[] selectedFiles = fileChooser.getSelectedFiles();
            if(selectedFiles != null && selectedFiles.length > 0) {
                for (File selectedFile : selectedFiles) {
                    paths += selectedFile.getAbsolutePath() + ",";
                }
                paths = paths.substring(0, (paths.length() - 1));
            }
            xmlField.setText(paths);
        }
    }

    public JButton getBrowseButton() {
        return browseButton;
    }

    public void setBrowseButton(JButton browseButton) {
        this.browseButton = browseButton;
    }

    public JTextField getClassesField() {
        return classesField;
    }

    public void setClassesField(JTextField classesField) {
        this.classesField = classesField;
    }

    public JTextField getDebuggerField() {
        return debuggerField;
    }

    public void setDebuggerField(JTextField debuggerField) {
        this.debuggerField = debuggerField;
    }

    public JTextField getRunOnPortField() {
        return runOnPortField;
    }

    public void setRunOnPortField(JTextField runOnPortField) {
        this.runOnPortField = runOnPortField;
    }

    public JTextField getWebappField() {
        return webappField;
    }

    public void setWebappField(JTextField webappField) {
        this.webappField = webappField;
    }

    public JTextField getXmlField() {
        return xmlField;
    }

    public void setXmlField(JTextField xmlField) {
        this.xmlField = xmlField;
    }

    public JTextField getPathField() {
        return pathField;
    }

    public void setPathField(JTextField pathField) {
        this.pathField = pathField;
    }

    // Variables declaration - do not modify
    private javax.swing.JButton browseButton;
    private javax.swing.JTextField classesField;
    private javax.swing.JLabel classesLabel;
    private javax.swing.JTextField debuggerField;
    private javax.swing.JLabel debuggerLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField pathField;
    private javax.swing.JLabel pathLabel;
    private javax.swing.JTextField runOnPortField;
    private javax.swing.JLabel runOnPortLabel;
    private javax.swing.JTextField webappField;
    private javax.swing.JLabel webappLabel;
    private javax.swing.JTextField xmlField;
    private javax.swing.JLabel xmlLabel;
    // End of variables declaration
}
